spring.application.name=budget-service
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]

# Neon PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/budget}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.max-lifetime=540000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.keepalive-time=45000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.security.user.name=admin
#spring.security.user.password={noop}admin123
#spring.security.user.roles=ADMIN

server.port=8081

# Internal service URLs
services.user-service.url=http://user-service

spring.devtools.restart.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

# Eureka configuration to allow multi-device network testing
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=${SERVER_IP:localhost}

# Kafka Configuration
spring.kafka.producer.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Redis Caching Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=300000
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
