name: Deploy All Services

on:
  workflow_run:
    workflows: ["Build and Push All Services"]
    types:
      - completed
    branches:
      - Jasmita
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Short Git SHA
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Copy deployment files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,docker-compose.infra.yml,scripts/deploy.sh"
          target: "/opt/artha"

      - name: SSH and run deploy script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GHCR_PAT,GHCR_USERNAME
          script: |
            chmod +x /opt/artha/scripts/deploy.sh
            
            export GHCR_PAT="${{ secrets.GHCR_PAT }}"
            export GHCR_USERNAME="${{ secrets.GHCR_USERNAME }}"
            
            /opt/artha/scripts/deploy.sh ${{ steps.vars.outputs.sha_short }}
